# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_dummy <- function(data, params, loss, frame, proj) {
    .Call(`_nExtJTRcpp_fit_dummy`, data, params, loss, frame, proj)
}

